### ISSUE TITLE
Robustness to point permutation and rigid transformation

### ISSUE THREAD

**Issue by ThreeWaterGG** [Yochengliu/Relation-Shape-CNN#42]
In 'Robustness to point permutation and rigid transformation' experiment, the article said 'we address this issue by normalizing each sampled point subset to corresponding local coordinate system, which is determined by each sampled point and its normal'.  But can't we use only normal vector to determine a local coordinate system?  Or would you demonstrate  the details of this process?

**Comment by Yochengliu** [comment]
We address this issue by normalizing (include rotating) each sampled point subset to corresponding local coordinate system, which is determined by **each sampled point (the centroid) and its normal**. In this way, all the local point subsets are normalized to their corresponding local coordinate systems that can result in the invariance to rotation. Yet note that the accuracy drops a lot, because this forcible normalization could bring difficulty for shape recognition.
